Issue #112: Select windows processes by user name and domain
sentrysoftware/metricshub-community-connectors pull request #147
Opened 2024-11-21 09:17 UTC by MedMaalej

* Update WindowsProcess.yaml

2024-11-21 09:23 UTC, NassimBtk requested changes
Format changed

2024-11-21 13:50 UTC, MedMaalej commented
I checked the logs, here is a sample output of the connector:

<img width="535" alt="WinProcess" src="https://github.com/user-attachments/assets/6ad92690-fe60-41c4-a8fb-536dd7f20f46">

It shows the processes of a given user selected using the regex matchUser and / or matchDomain in the connector file.
The screenshot confirms that we retrieved successfully the domain and the user of the account associated to a given process.

The configuration in `metricshub.yaml` was as below:

```
resources:
  localhost:
    attributes:
      host.name: localhost
      host.type: win
    protocols:
      wmi:
        timeout: 120
    connectors: [+WindowsProcess]
```

2024-11-25 14:15 UTC, NassimBtk approved these changes

2024-11-25 14:16 UTC, NassimBtk commented
@bertysentry what do you think ?

2024-12-05 12:10 UTC, bertysentry approved these changes

2024-12-05 12:11 UTC, merged