Issue #148: [Linux] Enhance filesystem utilization calculation
sentrysoftware/metricshub-community-connectors pull request #149
Opened 2024-11-21 15:40 UTC by NassimBtk

This pull request includes an important update to the `src/main/connector/system/Linux/Linux.yaml` file, specifically within the `monitors` section. The change modifies the `awk` script used for processing disk usage information.

Key change:

* [`src/main/connector/system/Linux/Linux.yaml`](diffhunk://#diff-6d6e70c25f3246a9ae9889d976c332be4895e49b0b7605cbabe6dbc9f2ab4fa9L153-R153): Updated the `awk` script to correctly calculate the percentage of used and available space by using the sum of used and available space as the denominator.

Testing:
![image](https://github.com/user-attachments/assets/4110008a-da33-4159-93ac-a0980beacfae)
```bash
root@nb-debian:/opt/workspace/opentelemetry-collector-contrib# /usr/bin/df -B1
Filesystem       1B-blocks        Used  Available Use% Mounted on
udev            2053718016           0 2053718016   0% /dev
tmpfs            413818880    41848832  371970048  11% /run
/dev/sda1      42091429888 32452136960 7574675456  82% /
tmpfs           2069078016           0 2069078016   0% /dev/shm
tmpfs              5242880           0    5242880   0% /run/lock
tmpfs           2069078016           0 2069078016   0% /sys/fs/cgroup
tmpfs            413814784           0  413814784   0% /run/user/0
```

2024-11-21 16:27 UTC, bertysentry requested changes

2024-11-21 22:21 UTC, NassimBtk commented on src/main/connector/system/Linux/Linux.yaml
> +            script: NR > 1 {print $1 "(" $2 ")" ";" $2 ";" $3 ";" $4 ";" $5 ";" $4 / ($4 + $5) ";" $5 / ($4 + $5)}
Yep I agree, let's add these two metrics.

2024-11-22 11:11 UTC, NassimBtk commented on src/main/connector/system/Linux/Linux.yaml
> +            script: NR > 1 {print $1 "(" $2 ")" ";" $2 ";" $3 ";" $4 ";" $5 ";" $4 / ($4 + $5) ";" $5 / ($4 + $5)}
Updated dashboard:
![image](https://github.com/user-attachments/assets/a924f8d1-3fef-4ab7-8933-b51609f697e5)

2024-11-22 11:12 UTC, NassimBtk commented on src/main/connector/system/Linux/Linux.yaml
> +            script: NR > 1 {print $1 "(" $2 ")" ";" $2 ";" $3 ";" $4 ";" $5 ";" $4 / ($4 + $5) ";" $5 / ($4 + $5)}
![image](https://github.com/user-attachments/assets/52523ed4-08b0-47a9-b228-780a2d5dc153)

2024-11-22 11:38 UTC, bertysentry approved these changes
I wonder whether we should update the system dashboards in Grafana. But this is good! 😅

Nothing like real life testing... 😉

2024-11-22 12:41 UTC, merged

2024-11-22 13:51 UTC, NassimBtk commented
System dashboards updates: https://github.com/sentrysoftware/grafana-dashboards/pull/26.